version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  backend:
    build: ./cms
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    entrypoint: ./scripts/entrypoint.sh
    volumes:
      - ./cms:/cms
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
    depends_on:
      - db
  frontend:
    build: ./cms-frontend
    command: npm run serve
    volumes:
      - ./cms-frontend:/app
    ports:
      - "8080:8080"

